---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAiYXV0aCI6ICJheTVyZFdSbGJHbGphRHBkV20xbE4wQlZhdz09IgogICAgICAgIH0KICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson 
